[project]
name = "pe-testing"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3",
    "pytest-asyncio>=0.24",
    "pytest-cov>=6.0",
    "httpx>=0.28",
    "factory-boy>=3.3",
    "sqlalchemy[asyncio]>=2.0",
    "asyncpg>=0.30",
    "pe-core",
    "pe-database",
]

[tool.uv.sources]
pe-core     = { workspace = true }
pe-database = { workspace = true }
