package com.enterprise.common.core.domain;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Base entity with audit fields and soft-delete support.
 * All domain entities should extend this class.
 */
@Getter
@Setter
public abstract class BaseEntity implements Serializable {

    /**
     * Primary key - snowflake ID generated by MyBatis-Plus.
     */
    @TableId(type = IdType.ASSIGN_ID)
    private Long id;

    /**
     * Creator user ID, auto-filled on insert.
     */
    @TableField(fill = FieldFill.INSERT)
    private Long createBy;

    /**
     * Creation timestamp, auto-filled on insert.
     */
    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createTime;

    /**
     * Last modifier user ID, auto-filled on update.
     */
    @TableField(fill = FieldFill.INSERT_UPDATE)
    private Long updateBy;

    /**
     * Last update timestamp, auto-filled on update.
     */
    @TableField(fill = FieldFill.INSERT_UPDATE)
    private LocalDateTime updateTime;

    /**
     * Soft delete flag: 0=active, 1=deleted.
     */
    @TableLogic
    @TableField(value = "deleted")
    private Integer deleted;
}
